#-------------------------------
# General Site Settings

title: Sam Mo Portfolio
#logo: logo.png
email: omojolasamsonade@gmail.com
phone: +880 2544 658 256
address: 125/A, CA Commercial Area, California, USA

menu:
- {name: About, link: '/about'}
- {name: Blog, link: '/blog'}
- {name: Portfolio, link: '/portfolio'}
- {name: Contact, link: 'contact.html'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I’m <br> Sam <br> Software Developer

social:
- {icon: "ti-github", link: "https://www.github.com/omojolasamson"}
- {icon: "ti-linkedin", link: "https://www.linkedin.com/in/samson-omojola-ba711056/"}
# - {icon: "ti-dribbble", link: "#"}
# - {icon: "ti-twitter", link: "#"}


#-------------------------------
# About (Section and Page)

# About Section
blurb:
  

#blurb-btn-link: '/about'
#blurb-btn-name: know more
# I, Samson commented out the two lines above

# About Page

# Work Process Section
work-process:
  - title : "Research and Plan"
    icon : "assets/images/icons/plan.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    
  - title : "Design and Develop"
    icon : "assets/images/icons/design.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    
  - title : "Deliver"
    icon : "assets/images/icons/print.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."


# My Team Section
team:
  - title : "Jack Schenziwe"
    image : "assets/images/team/member-1.png"
    designation : "Project Manager"
    
  - title : "Julias Carlie"
    image : "assets/images/team/member-2.png"
    designation : "Web Developer"
    
  - title : "John Doe"
    image : "assets/images/team/member-3.png"
    designation : "Designer"


#-------------------------------
# Skills Section

skills-title: Skills
skills:
- {name: Backend Development, color: '#fdb157', value: '90%'}
- {name: Frontend Development, color: '#9473e6', value: '85%'}
- {name: Technical Writing, color: '#bdecf6', value: '90%'}
- {name: Mobile App, color: '#ffbcaa', value: '90%'}


#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
- {name: Software Developer Intern, icon: 'icon-1.png', date: 'Jan - Oct 2017', organization: 'Braintemple, Yaba, Lagos'}
- {name: Freelancer, icon: 'icon-3.png', date: 'Oct 2017 - May 2019', organization: 'Fiverr'}
- {name: Software Developer, icon: 'icon-2.png', date: 'Feb 2020 - present', organization: 'Microsoft, Lagos'}


#-------------------------------
# Education Section

education-title: Education
education:
- {name: Bachelor's degree in Electrical/Electronics Engineering, date: '2018', organization: 'University of Ilorin'}
- {name: Secondary School Certificate, date: '2012', organization: 'Government Secondary School, Kubwa'}
# - {name: Higher Secondary Certificat, date: '2000', organization: 'Cardiff School'}
# - {name: Secondary School Certificate, date: '1998', organization: 'Cardiff School'}


# #-------------------------------
# # Services Section

# services-title: Services
# services:
# - {
#     name: UI Design,
#     icon: ti-palette,
#     description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
#     active: # Add true to select section
#   }
# - {
#     name: UX Design,
#     icon: ti-vector,
#     description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
#     active: true # Add true to select section
#   }
# - {
#     name: Interaction Design,
#     icon: ti-panel,
#     description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
#     active: # Add true to select section
#   }



# #-------------------------------
# # Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image : "assets/images/portfolio/item-1.png"
    url: "http://learnfast24.herokuapp.com"
    
  - image : "assets/images/portfolio/item-2.png"
    url: "http://directory365.herokuapp.com"
    
  - image : "assets/images/portfolio/item-3.png"
    url: "http://jadastouch.herokuapp.com"
    
  - image : "assets/images/portfolio/item-4.png"
    url: "http://eppme.herokuapp.com"
    
  - image : "assets/images/portfolio/item-5.png"
    url: "http://buxhub.herokuapp.com"
  
  - image : "assets/images/portfolio/Screenshot (240).png"
    url: "http://tronicmarket.herokuapp.com"

  - image : "assets/images/portfolio/Screenshot (241).png"
    url: "https://digitechnigeria.netlify.app/"

  - image : "assets/images/portfolio/item-7.png"
    url: "http://homezoneglobal.herokuapp.com"
    

    
    
    
# Portfolio Contributed Section
portfolio-contributed-items:
  - image : "assets/images/portfolio/item-8.png"
    url: "https://play.google.com/store/apps/details?id=buyer.emakity.com"
    
  - image : "assets/images/portfolio/item-9.png"
    url: "https://play.google.com/store/apps/details?id=delivery.emakity.com"
    
  - image : "assets/images/portfolio/item-10.png"
    url: "https://play.google.com/store/apps/details?id=storemanager.emkity.com"
  

    
    

# Portfolio webContributed Section
portfolio-webcontributed-items:
  - image : "assets/images/portfolio/item-11.png"
    url: "https://hultprize-oncampus.org"
    
  - image : "assets/images/portfolio/item-12.png"
    url: "https://www.emakity.com"
    
  - image : "assets/images/portfolio/item-12.png"
    url: "https://www.emakity.com"

    
    

# Portfolio Page
portfolio-label:
- {
    title : "Website Development",
    type : "design"
  }
- {
    title : "Mobile Development",
    type : "branding"
  }
# - {
#     title : "ILLUSTRATION",
#     type : "illustration"
#   }

portfolio-items:
  - image : "assets/images/portfolio/item-11.png"
    url: "https://hultprize-oncampus.org"
    portfolio-type:
     - type: "design"
      
  - image : "assets/images/portfolio/item-12.png"
    url: "https://www.emakity.com"
    portfolio-type:
      - type: "design"
      
  - image : "assets/images/portfolio/item-1.png"
    url: "http://learnfast24.herokuapp.com"
    portfolio-type:
      - type: "design"
      
  - image : "assets/images/portfolio/item-4.png"
    url: "http://eppme.herokuapp.com"
    portfolio-type:
      - type: "design"
      
  - image : "assets/images/portfolio/item-2.png"
    url: "http://directory365.herokuapp.com"
    portfolio-type:
      - type: "design"
      
  - image : "assets/images/portfolio/item-3.png"
    url: "http://jadastouch.herokuapp.com"
    portfolio-type:
      - type: "design"
      
  - image : "assets/images/portfolio/item-7.png"
    url: "http://homezoneglobal.herokuapp.com"
    portfolio-type:
      - type: "design"
      
  - image : "assets/images/portfolio/item-5.png"
    url: "http://buxhub.herokuapp.com"
    portfolio-type:
      - type: "design"
      
  - image : "assets/images/portfolio/Screenshot (241).png"
    url: "https://digitechnigeria.netlify.app/"
    portfolio-type:
      - type: "design"
      
  - image : "assets/images/portfolio/Screenshot (240).png"
    url: "http://tronicmarket.herokuapp.com"
    portfolio-type:
      - type: "design"
      
  - image : "assets/images/portfolio/item-8.png"
    url: "https://play.google.com/store/apps/details?id=buyer.emakity.com"
    portfolio-type:
      - type: "branding"
      
  - image : "assets/images/portfolio/item-9.png"
    url: "https://play.google.com/store/apps/details?id=delivery.emakity.com"
    portfolio-type:
      - type: "branding"

      
  - image : "assets/images/portfolio/item-10.png"
    url: "https://play.google.com/store/apps/details?id=storemanager.emkity.com"
    portfolio-type:
      - type: "branding"


#-------------------------------

# testimonial-items:
#   - name: "Jesica Gomez"
#     image: "assets/images/testimonial/client-1.png"
#     designation : "CEO, Funder"
#     content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
    
#   - name: "Jesica Gomez"
#     image: "assets/images/testimonial/client-1.png"
#     designation: "CEO, Funder"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
    
#   - name: "Jesica Gomez"
#     image: "assets/images/testimonial/client-1.png"
#     designation: "CEO, Funder"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."


# #-------------------------------
# # Client Slider Section

# client-slider-items:
#   - logo: "assets/images/clients-logo/client-logo-1.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-2.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-3.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-4.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-5.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-1.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-2.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-3.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-4.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-5.png"
#     url: "#"

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: omojolasamsonade@gmail.com
